---
- name: Format Subject Alt Names (list of dictionaries)
  block:
    - name: Add host shortname to SAN dict
      ansible.builtin.set_fact:
        san_list: >-
          {{
            san_list | default([]) +
            [{
              "TypeName": "DNS",
              "Name": "{{ ansible_hostname }}"
            }]
          }}
    - name: Add host fqdn to SAN dict
      ansible.builtin.set_fact:
        san_list: >-
          {{
            san_list +
            [{
              "TypeName": "DNS",
              "Name": ansible_fqdn
            }]
          }}
    - name: Add custom subalts to SAN dict
      ansible.builtin.set_fact:
        san_list: >-
          {{
            san_list +
            [{
              "TypeName": "DNS",
              "Name": item
            }]
          }}
      loop: "{{ subalt_names }}"
    - name: Add IP addresses to SAN dict
      ansible.builtin.set_fact:
        san_list: >-
          {{
            san_list +
            [{
              "TypeName": "IPAddress",
              "Name": item
            }]
          }}
      loop: "{{ ansible_all_ipv4_addresses }}"

- name: Dump san details
  ansible.builtin.debug:
    msg: "{{ san_list }}"
  when: debug_mode|bool
