---
- name: Check Venafi credential is present
  ansible.builtin.fail:
    msg: "Venafi credentials appear to be missing, check you have added you Venafi service account credentials"
  when: venafi_user is undefined

- name: Get facts for subalts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - network
- ansible.builtin.set_fact:
    venafi_zone: "{{ override_venafi_zone }}"
  when: (override_venafi_zone is defined) and (override_venafi_zone | length > 0)
- ansible.builtin.set_fact:
    venafi_working_dir: "{{ override_working_dir }}"
  when: (override_working_dir is defined) and (override_working_dir | length > 0)
- ansible.builtin.set_fact:
    format: "Base64"
  when: cert_format | lower == "base64"
- ansible.builtin.set_fact:
    format: "JKS"
  when: cert_format | lower == "jks"
- ansible.builtin.set_fact:
    format: "PKCS #12"
  when: cert_format | lower == "pkcs12"
- ansible.builtin.debug:
    msg: "Cert format will be {{ format }}"
- name: Ensure cert directory exists
  ansible.builtin.file:
    path: "{{ venafi_working_dir }}"
    state: directory
- ansible.builtin.include_tasks: authenticate.yml
- ansible.builtin.include_tasks: format_san_list.yml
- ansible.builtin.include_tasks: request_certs.yml
- name: Pause for cert generation to complete
  ansible.builtin.pause:
    seconds: 60
- ansible.builtin.include_tasks: retrieve_certs.yml
- ansible.builtin.include_tasks: revoke_auth.yml
- ansible.builtin.include_tasks: process_cert_files.yml
  when: retrieve_cert_reg.status == 200
